default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: posterchild_dev

test:
  <<: *default
  database: psoterchild_test

production:
  <<: *default
  database: posterchild
